apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/oxygen-cs-grp1-eq7-default: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: HOST
              value: https://hvac-simulator-a23-y2kpq.ondigitalocean.app
            - name: TOKEN
              value: 9vXWwTEL39
            - name: T_MAX
              value: "100"
            - name: T_MIN
              value: "0"
          image: log680equipe7/oxygen-cs:latest
          name: oxygen-cs
          ports:
            - containerPort: 80
              # hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
