version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    # environment:
    #   TZ: ${TZ}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432


  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL : admin@admin.com
      PGADMIN_DEFAULT_PASSWORD : admin
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    ports:
      - 5000:80
    depends_on:
      - postgres


  app:
    image: ${DOCKERHUB_USERNAME}/oxygen-cs:1.0
    build:
      context: . 
      dockerfile: Dockerfile
    environment:
      HOST: ${HOST}
      TOKEN: ${TOKEN}
      T_MAX: ${T_MAX}
      T_MIN: ${T_MIN}
    ports:
      - 8000:8000
    depends_on:
      - postgres
