name: CI-CD Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run unit tests
    #   run: |
    #     pytest

    - name: Code static analysis and formatting
      run: |
        pip install pylint black
        find src -name '*.py' | xargs pylint
        black src
        
  # docker_build:
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Build Docker image
  #     run: |
  #       docker build -t oxygen-cs:latest -t oxygen-cs:1.0 .
        
  # docker_deploy:
  #   needs: docker_build
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Deploy to DockerHub
  #     run: |
  #       docker push oxygen-cs:latest
  #       docker push oxygen-cs:1.0
