name: Build Docker Image

on:
  push:
      branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3   
      with:
        push: false
        tags: oxygen-cs:1.0
