name: Build Docker Image

on:
  push:
      branches:
      - feature/14/workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run unit tests
      run: |
        pytest

    - name: Code static analysis and formatting
      run: |
        pip install black
        pip install "pylint==v3.0.2"
        find src -name '*.py' | xargs pylint --rcfile=.pylintrc
        black src
        
    - name: Prevent push on failure
      if: failure()
      run: exit 1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker-compose
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Push the app image to Docker Hub
      run: docker-compose -f "docker-compose.yml" push app

    - name: Start all services
      run: docker-compose -f "docker-compose.yml" up -d
